version: "3.3"

services:

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    network_mode: host
    restart: "always"
    command:
      - --log.level=$LOG_LEVEL
      - --global.sendAnonymousUsage=false
      - --api.insecure=$API_INSECURE
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=dyn.toml
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=$EMAIL
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    volumes:
      - $CERTIFICATES_DIRECTORY:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dyn.toml:/dyn.toml
